FROM node:22-alpine AS build

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable && corepack prepare pnpm@10.15.1 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm --version && pnpm install --frozen-lockfile

COPY . .

ENV CI=true

ARG NUXT_PUBLIC_API_KEY=
ENV NUXT_PUBLIC_API_KEY=$NUXT_PUBLIC_API_KEY

RUN pnpm run generate

FROM nginx:alpine

COPY --from=build /app/.output/public /usr/share/nginx/html
COPY nginx.prod.conf.template /etc/nginx/templates/default.conf.template
COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
